version: '1.0'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
  web:
    build: .
    command: ./backend/docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    depends_on:
      - db
