version: '3.0'
services:
  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    #restart: always
    #container_name: app-jamco
    #image: speuce/jamco:prod
    command: ./docker-entrypoint.sh
    ports:
      - "80:8000"
    environment:
      POSTGRES_NAME: ${RDS_DB_NAME:-postgres}
      POSTGRES_USER: ${RDS_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${RDS_PASSWORD:-admin}
      POSTGRES_HOST: ${RDS_HOSTNAME:-db}
      POSTGRES_PORT: ${RDS_PORT:-5432}
      PROD: ${PROD:-1}