version: '1.0'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./docker-entrypoint.sh
    volumes:
      - ./backend:/backend
      - ./frontend/dist:/static/dist
    ports:
      - "8000:8000"
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ./docker-entrypoint.sh
    #command: tail -f /dev/null
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
