# Generated by Django 4.1.5 on 2023-02-14 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_birthday_alter_user_city_and_more"),
        ("account", "0002_kanbancolumn"),
    ]

    operations = []
