# Generated by Django 4.1.5 on 2023-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_merge_20230214_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
