# Generated by Django 4.1.5 on 2023-02-21 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_alter_job_kcolumn"),
        ("account", "0004_user_region"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KanbanColumn",
        ),
    ]
