# Generated by Django 4.1.5 on 2023-02-21 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
