# Generated by Django 4.1.5 on 2023-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_demouser"),
    ]

    operations = [
        migrations.AddField(
            model_name="demouser",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
