# Generated by Django 4.1.5 on 2023-03-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_friendrequest_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="field_of_work",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
