# Generated by Django 4.1.5 on 2023-02-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_kcolumn"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.TextField(null=True),
        ),
    ]
