# Generated by Django 4.1.5 on 2023-02-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("column", "0001_initial"),
        ("job", "0003_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="kcolumn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="column.kanbancolumn"
            ),
        ),
    ]
