name: Backend Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  base_branch_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    env:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: '127.0.0.1'
      PROD: 0
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Generate Coverage Report
      run: coverage run --source='.' manage.py test
    - name: Convert Coverage Report to Lcov
      run: coverage lcov
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: ref-lcov.info
        path: ./backend/coverage.lcov
        
  checks:
    needs: base_branch_coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    env:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: '127.0.0.1'
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Download code coverage report from base branch
      uses: actions/download-artifact@v2
      with:
        name: ref-lcov.info
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Generate Coverage Report
      run: coverage run --source='.' manage.py test
    - name: Convert Coverage Report to Lcov
      run: coverage lcov
    #  Compares two code coverage files and generates report as a comment
    - name: Backend Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "./backend/coverage.lcov"
        base-lcov-file: "./coverage.lcov"
        minimum-ratio: 0.5
        send-summary-comment: true
        show-annotations: "warning" # Possible options warning|error
        app-name: "Backend"

